using SOFA_bioscoop.Application.Reporting;
using SOFA_bioscoop.Domain.Reporting;
using SOFA3_bioscoop.Test.Fakes;
using Xunit;

namespace SOFA3_bioscoop.Test
{
    public class SprintReportFactoryTests
    {
        [Fact]
        public void Factory_ShouldCreateSprintReport_FromGenerateReport()
        {
            var recording = new RecordingExportStrategy();
            var factory = new SprintReportFactory(recording);

            SprintReport report = factory.generateReport(sprint: null);

            Assert.IsType<SprintReport>(report);
            Assert.Equal("SOFA Company", report.companyName);
            Assert.Equal("Unknown Project", report.projectName);
            Assert.False(string.IsNullOrEmpty(report.content));
        }

        [Fact]
        public void GenerateReport_WithSprint_UsesSprintProjectName()
        {
            var factory = new SprintReportFactory(new RecordingExportStrategy());
            var report = factory.generateReport(sprint: null);
            Assert.Equal("Unknown Project", report.projectName);
        }

        [Fact]
        public void GenerateDecoratedReport_AppliesHeaderAndFooter_InOrder()
        {
            var factory = new SprintReportFactory(new RecordingExportStrategy());
            var header = new ReportHeaderData("HCo", "HPr", "1.0", "today", "lg");
            var footer = new ReportFooterData("me", "note");

            SprintReport report = factory.generateDecoratedReport(null, header, footer);

            Assert.Contains("========== HEADER ==========", report.content);
            Assert.Contains("========== FOOTER ==========", report.content);
            Assert.Contains("Company: HCo", report.content);
            Assert.Contains("Generated by: me", report.content);
            int headerPos = report.content.IndexOf("========== HEADER");
            int footerPos = report.content.IndexOf("========== FOOTER");
            Assert.True(headerPos < footerPos, "Header block should appear before footer block");
        }

        [Fact]
        public void ExportReport_ShouldCallStrategy_WithReportContent()
        {
            var strategy = new RecordingExportStrategy();
            var factory = new SprintReportFactory(strategy);
            SprintReport report = factory.generateReport(null);

            factory.exportReport(report);

            Assert.Equal(report.content, strategy.LastContent);
        }

        [Fact]
        public void Strategy_TwoFactories_UseDifferentStrategyInstances()
        {
            var strategyA = new RecordingExportStrategy();
            var strategyB = new RecordingExportStrategy();
            var factoryA = new SprintReportFactory(strategyA);
            var factoryB = new SprintReportFactory(strategyB);
            var report = factoryA.generateReport(null);

            factoryA.exportReport(report);
            factoryB.exportReport(report);

            Assert.Equal(report.content, strategyA.LastContent);
            Assert.Equal(report.content, strategyB.LastContent);
            Assert.NotSame(strategyA, strategyB);
        }
    }
}
