using System.Text;
using SOFA_bioscoop.Domain.Reporting;

namespace SOFA_bioscoop.Application.Reporting
{
    public class FooterDecorator : SprintReportDecorator
    {
        private ReportFooterData footerData;

        public FooterDecorator(ISprintReport wrappedReport, ReportFooterData footerData)
            : base(wrappedReport)
        {
            this.footerData = footerData;
        }

        public override string GenerateReport()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append(wrappedReport.GenerateReport());
            sb.AppendLine();
            sb.AppendLine("========== FOOTER ==========");
            sb.AppendLine("Generated by: " + footerData.generatedBy);
            sb.AppendLine("Notes: " + footerData.notes);
            sb.AppendLine("============================");
            return sb.ToString();
        }
    }
}
